sudo: false
language: node_js
node_js:
- '4'
before_install:
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
after_success:
- npm run coveralls
deploy:
  on:
    tags: true
  provider: npm
  email: sesispla@outlook.com
  api_key: Bw8TW7yQ7KcZtBZG9tTjvirVmnA21cPK6Iv/kv0UNO3LDr1HjdIYK+faF5tvT91UjkE8pyo8TXYbOy07yBfuTex7RdyS7hsIipsSFztByrw1vqjoJBrkXyXxcmtF1vsrNHX8j9uer7uJgLLGc9tiseh+ol5KNosafyWu42T/5kvJr+B2SOdE49TOc48mdpAeQkwDz9MiHHiefAybs8MQ9DiD6EbTQbf2gwKJYqXk/t7d4+E4BPv0nmRL9kQHGtH1Y2dsQea8rkcNrOP+0n0iLvaTuaYXrQGICV62QJb1Jj25KK3dmHPd/pmjMbTk/CA50vsgovwsBcZFpOOYLgC6jcmYFL6MLxGlhaOkU/CefNUhR7MPb5tT/yrEvBBEF2+W+gpCsd7sTq4BWiY7L9dfPs+IsNxYjPPIAd5qP1DWtyvJ6C19VI8znWnE652LOGXwJLjHrGPvEtrXCLfp7+Rsll6MhiBKLLr+R6UYfJwW5P/WEDf4UPyoVQC5W06GZKcdSbZf67AuKpn1woVjuCLoDyagjbAFKf8n59Wf1i2FF3TMBvZnfiyuU6KzHxTmf9pPlVHGtDj8924dxopvJE4Gc5eEmaTi4ZGlAis3vUG0yQlruFOdS4uRsNblT3ra2BN/R637ryHoF74UO8pKJ0tEkhTFGBmZwOktQozyeg8IVU0=  